EduToyRentalPlatform/Pages/Admin/FeedBack/Create.cshtml.cs
using ToyShop.Contract.Services.Interface;
using ToyShop.ModelViews.FeedBackModelViews;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToyShop.Pages.FeedBack
{
    public class CreateModel : PageModel
    {
        private readonly IFeedBackService _feedBackService;

        public CreateModel(IFeedBackService feedBackService)
        {
            _feedBackService = feedBackService;
        }

        [BindProperty]
        public CreateFeedBackModel Feedback { get; set; }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || Feedback == null)
            {
                return Page();
            }

            var feedback = new CreateFeedBackModel
            {
                UserId = Feedback.UserId,
                ToyId = Feedback.ToyId,
                Content = Feedback.Content
            };

            await _feedBackService.CreateFeedBackAsync(feedback);
            return RedirectToPage("Index");
        }
    }
}

EduToyRentalPlatform/Pages/Admin/FeedBack/Delete.cshtml.cs
using ToyShop.Contract.Services.Interface;
using ToyShop.ModelViews.FeedBackModelViews;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToyShop.Pages.Admin.FeedBack
{
    public class DeleteModel : PageModel
    {
        private readonly IFeedBackService _feedBackService;

        public DeleteModel(IFeedBackService feedBackService)
        {
            _feedBackService = feedBackService;
        }

        public ResponeFeedBackModel Feedback { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                throw new ArgumentNullException(nameof(id), "Feedback ID cannot be null or empty.");
            }

            Feedback = await _feedBackService.GetFeedBackAsync(id);
            if (Feedback == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            await _feedBackService.DeleteFeedBackAsync(id);
            return RedirectToPage("Index");
        }
    }
}

EduToyRentalPlatform/Pages/Admin/FeedBack/Details.cshtml.cs
using ToyShop.Contract.Services.Interface;
using ToyShop.ModelViews.FeedBackModelViews;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToyShop.Pages.Admin.FeedBack
{
    public class DetailsModel : PageModel
    {
        private readonly IFeedBackService _feedBackService;

        public DetailsModel(IFeedBackService feedBackService)
        {
            _feedBackService = feedBackService;
        }

        public ResponeFeedBackModel Feedback { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Lấy thông tin phản hồi từ service dựa trên id
            var responseFeedback = await _feedBackService.GetFeedBackAsync(id);

            if (responseFeedback == null)
            {
                return NotFound();
            }

            Feedback = responseFeedback; // Bind dữ liệu vào model

            return Page(); // Trả về trang Details
        }
    }
}

EduToyRentalPlatform/Pages/Admin/FeedBack/Edit.cshtml.cs
using ToyShop.Contract.Services.Interface;
using ToyShop.ModelViews.FeedBackModelViews;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace ToyShop.Pages.Admin.FeedBack
{
    public class EditModel : PageModel
    {
        private readonly IFeedBackService _feedBackService;

        public EditModel(IFeedBackService feedBackService)
        {
            _feedBackService = feedBackService;
        }
        [BindProperty]
        public ResponeFeedBackModel Feedback { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            var responseFeedback = await _feedBackService.GetFeedBackAsync(id);

            if (responseFeedback == null)
            {
                return NotFound();
            }

            Feedback = responseFeedback;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || Feedback == null)
            {
                return Page();
            }

            // Tạo đối tượng feedbackToUpdate từ Feedback
            var feedbackToUpdate = new ResponeFeedBackModel
            {
                UserId = Feedback.UserId, // Sử dụng giá trị từ Feedback
                ToyId = Feedback.ToyId, // Sử dụng giá trị từ Feedback
                Content = Feedback.Content
            };

            // Gọi phương thức cập nhật
            await _feedBackService.UpdateFeedBackAsync(Feedback.Id, feedbackToUpdate);
            return RedirectToPage("Index");
        }
    }
}

EduToyRentalPlatform/Pages/Admin/FeedBack/Index.cshtml.cs
using ToyShop.Contract.Services.Interface;
using ToyShop.ModelViews.FeedBackModelViews;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToyShop.Pages.Admin.FeedBack
{
    public class IndexModel : PageModel
    {
        private readonly IFeedBackService _feedBackService;

        public IndexModel(IFeedBackService feedBackService)
        {
            _feedBackService = feedBackService;
        }

        public IList<ResponeFeedBackModel> Feedbacks { get; set; }

        public int TotalItems { get; set; }  
        public int PageNumber { get; set; }
        public int PageSize { get; set; }

        public async Task OnGetAsync(int pageNumber = 1, int pageSize = 10)
        {
            var feedbackList = await _feedBackService.GetFeedBacks_AdminAsync(pageNumber, pageSize, null);
            Feedbacks = feedbackList.Items.ToList();
            TotalItems = feedbackList.TotalItems;  
            PageNumber = pageNumber;
            PageSize = pageSize;
        }
    }
}

EduToyRentalPlatform/Pages/Contract.cshtml.cs
using ToyShop.Contract.Repositories.Entity;
using ToyShop.Core.Base;
using ToyShop.ModelViews.ContractModelView;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ToyShop.Contract.Services.Interface;

namespace ToyShop.Pages
{
    public class ContractModel : PageModel
    {

        private readonly IContractService _contractService;
        public BasePaginatedList<ToyShop.Contract.Repositories.Entity.ContractEntity>? Contracts { get; set; }
        public ContractModel(IContractService contractService)
        {
            _contractService = contractService;
        }
        public async Task OnGetAsync([FromRoute] int index = 1, [FromRoute] int size = 5)
        {
            Contracts = await _contractService.GetContractsAsync(index, size);
        }

        public async Task<IActionResult> OnPutAsync(string id, [FromForm] UpdateContractModel contract)
        {
            try
            {
                await _contractService.UpdateContractAsync(id, contract);
            }
            catch (BaseException ex)
            {
                return BadRequest(ex.Message);
            }
            return Content("Thành công");
        }

        public async Task<IActionResult> OnDeleteAsync([FromBody] string? id)
        {
            try
            {
                await _contractService.DeleteContractAsync(id);
            }
            catch (BaseException ex)
            {
                return BadRequest("Có lỗi");
            }
            return Content("Xóa thành công");
        }

        [BindProperty]
        private CreateContractModel createNewContract { get; set; }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            try
            {
                await _contractService.CreateContractAsync(createNewContract);
            }
            catch (BaseException ex)
            {
                return BadRequest(ex.Message);
            }
            return Content("Thêm thành công");
        }
    }
}

EduToyRentalPlatform/Pages/FeedBack.cshtml.cs
using ToyShop.Contract.Services.Interface;
using ToyShop.ModelViews.FeedBackModelViews;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToyShop.Pages
{
    public class FeedBackModel : PageModel
    {
        private readonly IFeedBackService _feedBackService;

        public FeedBackModel(IFeedBackService feedBackService)
        {
            _feedBackService = feedBackService;
        }

        [BindProperty]
        public CreateFeedBackModel Feedback { get; set; }
        public List<ResponeFeedBackModel> Feedbacks { get; set; } = new List<ResponeFeedBackModel>();

        // Phân trang
        public int TotalItems { get; set; }
        public int PageNumber { get; set; }
        public int PageSize { get; set; }
        public int TotalPages { get; set; }

        public async Task OnGetAsync(int pageNumber = 1, int pageSize = 4)
        {
            var feedbackList = await _feedBackService.GetFeedBacksAsync(pageNumber, pageSize, null);
            Feedbacks = feedbackList.Items.ToList();
            TotalItems = feedbackList.TotalItems;
            PageNumber = pageNumber;
            PageSize = pageSize;
            TotalPages = feedbackList.TotalPages; // Set total pages
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || Feedback == null)
            {
                return Page();
            }

            var feedback = new CreateFeedBackModel
            {
                UserId = Feedback.UserId, 
                ToyId = Feedback.ToyId,
                Content = Feedback.Content
            };

            await _feedBackService.CreateFeedBackAsync(feedback);
            return RedirectToPage("FeedBack");
        }
    }
}

EduToyRentalPlatform/Pages/Message.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ToyShop.Contract.Services.Interface;
using ToyShop.ModelViews.MessageModelViews;

namespace ToyShop.Pages
{
    public class MessageModel : PageModel
    {
        private readonly IMessageService _messageService;

        public MessageModel(IMessageService messageService)
        {
            _messageService = messageService;
        }

        public List<MessageViewModel> Messages { get; set; } = new List<MessageViewModel>();

        public async Task OnGetAsync()
        {
            Messages = (List<MessageViewModel>)await _messageService.GetAllAsync();
        }

        public async Task<IActionResult> OnPostSendMessageAsync(string messageInput)
        {
            if (!string.IsNullOrWhiteSpace(messageInput))
            {
                var newMessage = new CreateMessageModel
                {
                    ChatId = "1", // ID của chat, có thể thay đổi theo thực tế
                    SenderId = "user123", // ID người gửi, có thể thay đổi theo thực tế
                    MessageText = messageInput
                };

                try
                {
                    await _messageService.AddAsync(newMessage); // Gọi dịch vụ để thêm tin nhắn
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Có lỗi xảy ra khi lưu tin nhắn: " + ex.Message);
                    return Page();
                }
            }

            return RedirectToPage(); // Quay lại trang hiện tại để làm mới danh sách tin nhắn
        }
    }
}

EduToyRentalPlatform/Pages/Shop.cshtml.cs
using ToyShop.Contract.Services.Interface;
using ToyShop.ModelViews.ToyModelViews;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToyShop.Pages
{
    public class ShopModel : PageModel
    {
        private readonly IToyService _toyService;

        public ShopModel(IToyService toyService)
        {
            _toyService = toyService;
        }

        public List<ResponeToyModel> ToysList { get; set; } = new List<ResponeToyModel>();

        public async Task OnGet()
        {
            var toys = await _toyService.GetToysAsync(1, 10, null);
            ToysList = toys.Items.ToList();
        }
    }
}

EduToyRentalPlatform/Pages/Contract.cshtml
@page "/Home/Contract/"
@using System.Collections;
@using AutoMapper;
@using ToyShop.ModelViews.ContractModelView;
@using ToyShop.Repositories.Base
@model ToyShop.Pages.ContractModel;
@inject IMapper _mapper

@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
    ViewData["Title"] = "Hợp đồng";
    int index = int.TryParse(Request.Query["index"].ToString(), out index) ? index : 1;
    int pageSize = int.TryParse(Request.Query["index"].ToString(), out pageSize) ? pageSize : 5;
    int size = Model.Contracts?.TotalItems ?? 1;
}
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-4">
                        <h2>Order <b>Details</b></h2>
                    </div>
                    <div class="col-sm-8">
                        <a href="#" onclick="location.reload()" class="btn btn-primary"><i class="fa fa-refresh" aria-hidden="true"></i> <span>Làm mới</span></a>
                        <button href="#" class="btn btn-secondary" id="addContractBtn"><i class="fa fa-plus"></i> <span>Thêm hợp đồng</span></button>
                    </div>
                    @await Html.PartialAsync("Partial/_contractCreateFormPartial.cshtml", new ResponseContractModel())
                </div>
            </div>
            <div class="table-filter">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="show-entries">
                            <span>Xem</span>
                            <select class="form-control" id="pagingOption">
                                <option disabled selected value="5">5</option>
                                <option value="10">10</option>
                                <option value="15">15</option>
                                <option value="20">20</option>
                            </select>
                            <span>entries</span>
                        </div>
                    </div>
                    <div class="filter-group">
                        <label>Loại</label>
                        <select class="form-control" id="typeOption">
                            <option selected disabled>Chọn loại HD</option>
                            <option value="rent">Thuê</option>
                            <option value="buy">Mua</option>
                        </select>
                    </div>
                    <div class="filter-group">
                        <label>Tình trạng</label>
                        <select class="form-control" id="statusOption">
                            <option selected disabled>Chọn status</option>
                            <option value="active">Còn hạn</option>
                            <option value="expired">Hết hạn</option>
                            <option value="pass">Duyệt</option>
                        </select>
                    </div>
                    <span class="filter-icon"><i class="fa fa-filter"></i></span>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover overflow-x-scroll">
            <thead>
                <tr>
                    <th>Mã hợp đồng</th>
                    <th>Ngày tạo</th>
                    <th>Đồ chơi</th>
                    <th>Tình trạng</th>
                    <th>Loại hợp đồng</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Contracts != null)
                {
                    @foreach (ToyShop.Contract.Repositories.Entity.ContractEntity con in Model.Contracts.Items)
                    {
                        if (size >= 0 && con != null)
                        {
                            ResponseContractModel view = _mapper.Map<ResponseContractModel>(con);
                            UpdateContractModel update = _mapper.Map<UpdateContractModel>(con);
                            <tr id="@con.Id" class='@(view.ContractType=="Thuê"?"rent":"buy")'>
                                <td>@con.Id</td>
                                <td>@con.DateCreated</td>
                                <td>@view.ToyName</td>
                                <td>@view.ContractType</td>
                                <td>
                                    <select class="form-control min-vw-10" id="editOption-@con.Id">
                                        <option selected disabled>Chọn</option>
                                        <option value="1">Cập nhật</option>
                                        <option value="2">Xóa</option>
                                        <option value="0">Xem</option>
                                    </select>
                                </td>
                                <td>
                                    <div id="contractUpdate-@con.Id" class="d-none">
                                        <form onclick="Update()" class="form-card p-3" action="/home/contract/?handler=OnPutAsync">
                                            <input type="hidden" name="id" id="id" value="@con.Id" />
                                            @await Html.PartialAsync("Partial/_updateContract.cshtml", update)
                                        </form>
                                    </div>
                                    <div id="contractView-@con.Id" onclick="this.classList.toggle('d-none')" class="d-none">
                                        @await Html.PartialAsync("Partial/_contractPartial.cshtml", view)
                                    </div>
                                </td>
                            </tr>

                            size--;
                        }
                        else
                        {
                            break;
                        }

                    }
                }
            </tbody>
        </table>
        <div class="clearfix">
            <div class="hint-text">Showing <b>5</b> out of <b>25</b> entries</div>
            <ul class="pagination">
                @if (index == 1)
                {
                    <li class="page-item disabled"><a href="">Previous</a></li>
                }
                else
                {
                    <li class="page-item"><a href="/hop-dong/(@index - 1)/(@pageSize)">Previous</a></li>
                }
                @for (int count = 1; count <= (size / index); count++)
                {
                    if (index == count)
                    {
                        <li class="page-item active"><a href="/hop-dong/(@count)/(@pageSize)" class="page-link">@count</a></li>
                    }
                    else
                    {
                        <li class="page-item"><a href="/hop-dong/(@count)/(@pageSize)" class="page-link">@count</a></li>
                    }
                }
                @if (index * pageSize > size)
                {
                    <li class="page-item disabled"><a href="#">Next</a></li>
                }
                else
                {
                    <li class="page-item"><a href="/hop-dong/(@index + 1)/(@pageSize)">Next</a></li>
                }
            </ul>
        </div>
    </div>
</div>
</div>
<script>

    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
        $('#addContractBtn').click(function () {
            $('#createContractForm').removeClass('d-none');
        });

        $('.close-form').click(function () {
            if (!$('#createContractForm').hasClass('d-none')) {
                $('#createContractForm').addClass('d-none');
            }
        });

        $('#pageItem').change(() => {
            $.ajax({
                url: '/home/contract?handler=OnGet/1/' + $(this).val(),    // URL
                method: 'GET',
                dataType: 'json',
                success: function (data) {
                },
                error: function (xhr, status, error) {
                    console.log("Error: " + error);
                }
            });
        });
        $('#typeOption').change(function () {
            var optValue = $(this).val();
            var getAllContract = $(".contractItem");
            for (let i = 0; i < getAllContract.Length; i++) {
                // xoa contract
                if (getAllContract[i].attr("class") == optValue) {
                    //getAllContract[i].delete();
                }
            }
        });
        $('select[id^="editOption"]').change(function () {
            var parts = $(this).attr("id").split('-');
            const optionValue = $(this).val();
            const idValue = parts.slice(1).join('-');
            const contractView = $('#contractView-' + idValue);
            const contractUpdate = $('#contractUpdate-' + idValue);
            if (optionValue == 1) {
                contractUpdate.removeClass("d-none");
            } else if (optionValue == 2) {
                var result = confirm("Bạn có chắc chắn muốn xóa ?");
                $(idValue).remove();
                if (result === true) {
                    $.ajax({
                        url: '/home/contract?handler=OnDeleteAsync',    // URL
                        method: 'DELETE',
                        data: { id: idValue },
                        dataType: 'json',
                        success: function (data) {
                            confirm("Thành công");
                        },
                        error: function (xhr, status, error) {
                            alert("Khong xoa duoc");
                        }
                    });
                }
            } else {
                contractView.removeClass('d-none');
            }
        })
    });
</script>

EduToyRentalPlatform/Pages/FeedBack.cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model ToyShop.Pages.FeedBackModel
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
    ViewData["Title"] = "Feedbacks";
}


<div class="feedback-container">
    <div class="feedback-form">
        <h2>Gửi Phản Hồi</h2>
        <form method="post">
            <input type="hidden" name="FeedBack.UserId" value="2F8B3243-FFF9-4ACB-8A76-7E0A4F739270" />
            <input type="hidden" name="FeedBack.ToyId" value="0C91447E-A1F2-4FB5-B1E5-52AC81D10E30" />
            <textarea asp-for="Feedback.Content" placeholder="Nội dung phản hồi" required></textarea>
            <button type="submit">Gửi Phản Hồi</button>
        </form>
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="feedback-alert">@TempData["SuccessMessage"]</div>
        }
    </div>

    <h2>Danh Sách Phản Hồi</h2>
    <ul class="feedback-list">
        @foreach (var feedback in Model.Feedbacks)
        {
            <li class="feedback-item">
                <strong>@feedback.UserId</strong> - @feedback.CreatedTime.ToString("g")
                <p>@feedback.Content</p>
            </li>
        }
    </ul>
    <div class="pagination">
        @if (Model.PageNumber > 1)
        {
            <a asp-page="FeedBack" asp-route-pageNumber="@(Model.PageNumber - 1)" class="btn btn-secondary"><i class="fas fa-chevron-left"></i></a>
        }

        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            <a asp-page="FeedBack" asp-route-pageNumber="@i" class="@(i == Model.PageNumber ? "btn btn-primary" : "btn btn-light")">@i</a>
        }

        @if (Model.PageNumber < Model.TotalPages)
        {
            <a asp-page="FeedBack" asp-route-pageNumber="@(Model.PageNumber + 1)" class="btn btn-secondary"><i class="fas fa-chevron-right"></i></a>
        }
    </div>
</div>

<style>
    .feedback-container {
        font-family: Arial, sans-serif;
        /* background-color: #f4f4f4; */
        margin: 0;
        padding: 0;
    }

    .feedback-form {
        margin-top: 12rem;
        margin-bottom: 2rem;
        padding: 20px;
        background: white;
        border-radius: 5px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    }

    .feedback-form h2,
    .feedback-container h2 {
        text-align: center;
        margin-bottom: 20px;
        font-size: 2rem;
        color: #333;
    }

    .feedback-form input[type="hidden"] {
        display: none;
    }

    .feedback-form textarea {
        width: 100%;
        height: 150px;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        resize: none;
        margin-bottom: 20px;
        font-size: 16px;
    }

    .feedback-form button {
        width: 100%;
        padding: 10px;
        background-color: #81c408 !important;
        color: white;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .feedback-form button:hover {
        background-color: #218838;
    }

    .feedback-alert {
        text-align: center;
        margin-bottom: 20px;
        color: #155724;
        background-color: #d4edda;
        border: 1px solid #c3e6cb;
        padding: 10px;
        border-radius: 5px;
    }

    .feedback-list {
        list-style-type: none;
        padding: 0;
    }

    .feedback-item {
        background-color: white;
        border: 1px solid #ddd;
        border-radius: 5px;
        padding: 15px;
        margin: 10px 0;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    .feedback-item strong {
        color: #007bff;
    }

    .feedback-item p {
        margin: 10px 0;
        color: #555;
    }

</style>

EduToyRentalPlatform/Pages/Message.cshtml
@page
@model ToyShop.Pages.MessageModel
@{
    Layout = "~/Pages/Admin/Shared/_Layout.cshtml"; 
    ViewData["Title"] = "Giao Diện Chat";
}

<div class="messmain">
    <div class="message-container" id="messageContainer">
        @foreach (var message in Model.Messages)
        {
            <div class="message-item">
                <div class="message-bubble">@message.MessageText</div>
                <div class="message-info">@message.CreatedTime.ToString("HH:mm")</div>
            </div>
        }
    </div>

    <form id="messageForm" method="post" asp-page-handler="SendMessage">
        <div class="form-group">
            <input type="text" id="messageInput" name="messageInput" class="form-control" placeholder="Gõ tin nhắn của bạn ở đây..." required>
            <button type="submit" class="btn btn-primary2">Gửi</button>
        </div>
    </form>
</div>

EduToyRentalPlatform/Pages/Shop.cshtml
@page
@model ToyShop.Pages.ShopModel
@{
	Layout = "~/Pages/Shared/_Layout.cshtml";
}

<!-- Single Page Header start -->
<div class="container-fluid page-header py-5">
    <h1 class="text-center text-white display-6">Shop</h1>
    <ol class="breadcrumb justify-content-center mb-0">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Pages</a></li>
        <li class="breadcrumb-item active text-white">Shop</li>
    </ol>
</div>
<!-- Single Page Header End -->
<!-- Fruits Shop Start-->
<div class="container-fluid fruite py-5">
    <div class="container py-5">
        <h1 class="mb-4">TẤT CẢ SẢN PHẨM</h1>
        <div class="row g-4">
            <div class="col-lg-12">
                <div class="row g-4">
                    <div class="col-xl-3">
                        <div class="input-group w-100 mx-auto d-flex">
                            <input type="search" class="form-control p-3" placeholder="keywords" aria-describedby="search-icon-1">
                            <span id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                        </div>
                    </div>
                    <div class="col-6"></div>
                    <div class="col-xl-3">
                        <div class="bg-light ps-3 py-3 rounded d-flex justify-content-between mb-4">
                            <label for="fruits">Default Sorting:</label>
                            <select id="fruits" name="fruitlist" class="border-0 form-select-sm bg-light me-3" form="fruitform">
                                <option value="volvo">Nothing</option>
                                <option value="saab">Popularity</option>
                                <option value="opel">Organic</option>
                                <option value="audi">Fantastic</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row g-4">                  
                    <div class="row g-4">
                        <!-- Load danh sách đồ chơi từ ToyListPartial -->
                        @await Html.PartialAsync("~/Pages/Shared/ToyListPartial.cshtml", Model.ToysList)
                    </div>
                       
                        <div class="col-12">
                            <div class="pagination d-flex justify-content-center mt-5">
                                <a href="#" class="rounded">&laquo;</a>
                                <a href="#" class="active rounded">1</a>
                                <a href="#" class="rounded">2</a>
                                <a href="#" class="rounded">3</a>
                                <a href="#" class="rounded">4</a>
                                <a href="#" class="rounded">5</a>
                                <a href="#" class="rounded">6</a>
                                <a href="#" class="rounded">&raquo;</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fruits Shop End-->